/* config-breezeway.h. Generated by cmake from config-breezeway.h.cmake */

/*
 * SPDX-FileCopyrightText: 2014 Hugo Pereira Da Costa <hugo.pereira@free.fr>
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef config_breezeway_h
#define config_breezeway_h

/* Define to 1 if XCB libraries are found */
#cmakedefine01 BREEZEWAY_HAVE_X11

#endif
